//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDexed.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NDexed.Domain.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already in the queue for this provider. .
        /// </summary>
        public static string AlreadyInQueue {
            get {
                return ResourceManager.GetString("AlreadyInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication scheme -{0}- is not supported.  Only Basic authentication is supported at this time.
        /// </summary>
        public static string AuthenticationSchemeNotSupported {
            get {
                return ResourceManager.GetString("AuthenticationSchemeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The credentials were not supplied in the expected format ([userName]:[password]).
        /// </summary>
        public static string CredentialFormatError {
            get {
                return ResourceManager.GetString("CredentialFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A customer already exists with the name -{0}-.  Cannot proceed..
        /// </summary>
        public static string CustomerNameInUse {
            get {
                return ResourceManager.GetString("CustomerNameInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authorization token is expired.
        /// </summary>
        public static string ExpiredToken {
            get {
                return ResourceManager.GetString("ExpiredToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authorization token is malformed.  Cannot authorize user..
        /// </summary>
        public static string MalformedAuthorizationToken {
            get {
                return ResourceManager.GetString("MalformedAuthorizationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response from operation -{0}- was expected to return a result, but the result is null.  Cannot proceed..
        /// </summary>
        public static string MisingResponseItem {
            get {
                return ResourceManager.GetString("MisingResponseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument -{0}- was not found, but is required.
        /// </summary>
        public static string MissingRequiredArgument {
            get {
                return ResourceManager.GetString("MissingRequiredArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument -{0}- has a null value, but the value is required..
        /// </summary>
        public static string MissingRequiredArgumentValue {
            get {
                return ResourceManager.GetString("MissingRequiredArgumentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute store does not contain the column -{0}- that is required for this operation.  Cannot proceed..
        /// </summary>
        public static string MissingRequiredAttribute {
            get {
                return ResourceManager.GetString("MissingRequiredAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the required data for registering a user was not found.  Please check your data and try again..
        /// </summary>
        public static string MissingUserData {
            get {
                return ResourceManager.GetString("MissingUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The atribute -{0}- that is required fro this operation has a null or empty value.  Cannot proceed..
        /// </summary>
        public static string MisssingRequiredAttributeValue {
            get {
                return ResourceManager.GetString("MisssingRequiredAttributeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter at least one field to search by.
        /// </summary>
        public static string NoSearchCriteria {
            get {
                return ResourceManager.GetString("NoSearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user&apos;s security token is expired.  Please re-authenticate..
        /// </summary>
        public static string SecurityTokenExpired {
            get {
                return ResourceManager.GetString("SecurityTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The security token was not found.  Cannot authenticate user..
        /// </summary>
        public static string SecurityTokenNotFound {
            get {
                return ResourceManager.GetString("SecurityTokenNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with the email address -{0}- already exists..
        /// </summary>
        public static string UserEmailInUse {
            get {
                return ResourceManager.GetString("UserEmailInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with this email address already exists..
        /// </summary>
        public static string UserExists {
            get {
                return ResourceManager.GetString("UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is not authorized to act on behalf of the customer indicated by the id provided..
        /// </summary>
        public static string UserNotAuthorizedForCustomer {
            get {
                return ResourceManager.GetString("UserNotAuthorizedForCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user does not have the required permission for this operation.  Cannot proceed..
        /// </summary>
        public static string UserNotAuthrorizedForPermission {
            get {
                return ResourceManager.GetString("UserNotAuthrorizedForPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user could be found with the credentials you provided.  Please use a unique email address as the user name for this request..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
