//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDexed.Messaging.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NDexed.Messaging.Resources.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style&gt;
        ///    body {
        ///        background-color: #fff;
        ///        margin:0px;
        ///        padding:0px;
        ///    }
        ///
        ///    .header
        ///    {
        ///        margin:0px;
        ///        padding:15px;
        ///        background-color:#ee283b;
        ///        height:65px;
        ///    }
        ///
        ///    .body
        ///    {
        ///        padding:25px;
        ///    }
        ///    div{
        ///        width:100%;
        ///    }
        ///&lt;/style&gt;
        ///&lt;div&gt;
        ///    &lt;div class=&quot;header&quot;&gt;
        ///        &lt;a href=&quot;NDexed.mobi&quot;&gt;&lt;img src=&quot;https://s3.amazonaws.com/NDexed.resources/logo.png&quot; alt=&quot;NDexed&quot;&gt;&lt;/a&gt;
        ///    &lt;/div&gt;
        ///    
        ///    &lt;div class=&quot;bo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OrderSubmittedTemplate {
            get {
                return ResourceManager.GetString("OrderSubmittedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style&gt;
        ///    body {
        ///        background-color: #fff;
        ///        margin:0px;
        ///        padding:0px;
        ///    }
        ///
        ///    .header
        ///    {
        ///        margin:0px;
        ///        padding-left:7px;
        ///        padding-top:7px;
        ///        background-color:#ee283b;
        ///        height:65px;
        ///    }
        ///
        ///    .body
        ///    {
        ///        padding:25px;
        ///    }
        ///    div{
        ///        width:100%;
        ///    }
        ///&lt;/style&gt;
        ///&lt;div&gt;
        ///    &lt;div class=&quot;header&quot;&gt;
        ///        &lt;a href=&quot;NDexed.mobi&quot;&gt;&lt;img src=&quot;https://s3.amazonaws.com/NDexed.resources/logo.png&quot; alt=&quot;NDexed&quot;&gt;&lt;/a&gt;
        ///    &lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ResetPasswordTemplate {
            get {
                return ResourceManager.GetString("ResetPasswordTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style&gt;
        ///    body {
        ///        background-color: #fff;
        ///        margin:0px;
        ///        padding:0px;
        ///    }
        ///
        ///    .header
        ///    {
        ///        margin:0px;
        ///        padding-left:7px;
        ///        padding-top:7px;
        ///        background-color:#ee283b;
        ///        height:65px;
        ///    }
        ///
        ///    .body
        ///    {
        ///        padding:25px;
        ///    }
        ///    div{
        ///        width:100%;
        ///    }
        ///&lt;/style&gt;
        ///&lt;div&gt;
        ///    &lt;div class=&quot;header&quot;&gt;
        ///        &lt;a href=&quot;NDexed.com&quot;&gt;&lt;img src=&quot;https://s3.amazonaws.com/ndexed.resources/logo.png&quot; alt=&quot;NDexed&quot;&gt;&lt;/a&gt;
        ///    &lt;/d [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UserRegistrationTemplate {
            get {
                return ResourceManager.GetString("UserRegistrationTemplate", resourceCulture);
            }
        }
    }
}
